### PR TITLE
fixed #522; broken check in theme processing

### LINKED ISSUE #522: Applying theme to document fragment causes object undefined error
This line in the themes closest function

https://github.com/jdorn/json-editor/blob/master/src/theme.js#L277

Blows up when testing an element that is a document fragment as the fragment does not resolve a function for matchKey.  This is only happening when trying to use the enum Source.

I seem to be able to work around it with this type of check on line 276, but I'm still not getting a drop down for the enum, so this may be simply shot circuiting necessary logic:
      if ((matchKey) && (elem[matchKey] !== undefined)) {

This is the schema that is blowing up:

```
{
      "id": "batteryDefintions",
      "type": "object",
      "properties": {
        "batteries": {
          "id": "batteries",
          "type": "array",
          "items": {
            "id": "0",
            "type": "object",
            "properties": {
              "name": {
                "id": "name",
                "type": "string"
              },
              "minVoltage": {
                "id": "minVoltage",
                "type": "integer"
              },
              "maxVoltage": {
                "id": "maxVoltage",
                "type": "integer"
              }
            },
            "required": [
              "name",
              "minVoltage",
              "maxVoltage"
            ]
          },
          "required": [
            "0"
          ]
        },
        "selectedBattery" : {
          "id" : "selectedBattery",
          "type" : "string",
          "watch" : {
            "batteryEnum" : "batteries"
          },
          "enumSource" : [{
            "source" : "batteryEnum",
            "value" : "{{item.name}}"
          }]
        }
      },
      "required": [
        "batteries",
        "selectedBattery"
      ]

    }
```

### PR DESCRIPTION
**Pull request by BrianAdams**
This appeared to be a simple missing object qualifier for the short circuit logic.  Added it in.

### CODE REVIEW

**Comment by jdorn** [comment]
matchKey is defined at the top of that file.  Did the current code cause an error for you?

**Comment by BrianAdams** [comment]
Yes. If the element  (in my case a document fragment) is being evaluated as does not have a matchkey function defined, the code crashes with element.matchkey being undefined.  To your point the matchkey variable that was originally being checked for existence is defined above which is why I am assuming it was guard code that was guarding the wrong thing.  Matckey vs element.matchkey.

**Comment by aneesv** [comment]
:+1:

**Comment by jdorn** [comment]
I still don't quite get what the original error was.  Do you have an example schema/code that replicates it?

In your code, `elem.matchKey` will always be undefined and that if block will never be reached.  If you change it to `elem[matchKey]` instead, it should behave as expected.

**Comment by BrianAdams** [comment]
Thanks for the catch.  The problem is that the code crashes if it processes an element that does not have the function specified in matchkey.  In this case, a "document fragment' element is getting iterated over, and is does not have a matching function nor a ParentNode.

**Comment by piascikj** [comment]
:+1:

**Comment by piascikj** [comment]
Woot!

**Pull request merged**
