### PR TITLE
Custom styling for required properties

### PR DESCRIPTION
**Pull request by lepinay**
Right now it's not possible to visually distinguish between required and not required fields at glance because all fields are displayed in bold text.
The goal of this PR is to allow users to visually customize required fields.

When a property is marked in the json schema as required:

``` json
{
  "title": "Person",
  "type": "object",
  "required":["name"], 
  "properties": {
    "name": {
      "type": "string",
      "description": "First and Last name",
      "minLength": 4,
      "default": "Jeremy Dorn"
    },
```

A new css class called "required" will be generated on the corresponding container:

``` html
<div data-schematype="string" data-schemapath="root.name" class="required"><div class="form-control">
```

If the field is not listed as required then the class won't be added.

### CODE REVIEW

**Comment by jdorn** [comment]
Wouldn't it be easier to just apply a class to the editor container?  That way you don't need to modify all the editor classes and themes, just the base setContainer method.

**Comment by lepinay** [comment]
@jdorn I see your point, I'm going to rework this. It's long time overdue :)

**Comment by lepinay** [comment]
@jdorn This is ready for you to review, code is a lot simpler now.

**Comment by lepinay** [comment]
@jdorn any chance to get this one merged soon ? it's a few lines of code :)

**Comment by lepinay** [comment]
@jdorn bumping this PR again.

**Pull request closed without merging**
